### ISSUE TITLE
Support for BCD

### ISSUE THREAD

**Issue by morrisonbrett** [bitpay/copay-recovery#108]
https://coinmarketcap.com/currencies/bitcoin-diamond/

ANOTHER Hard fork.  Will you be adding support for Bitcoin Diamond? Would love to "claim" my BCD balance pre-fork.

**Comment by morrisonbrett** [comment]
Closing until a real BCD core client is available.

**Comment by PxSonny** [comment]
Is there now? I would be interested to retrieve my BCD now.

**Comment by SonnyAD** [comment]
Is there now? I would be interested to retrieve my BCD now.
