### ISSUE TITLE
Recovery problem!  - I need source code!

### ISSUE THREAD

**Issue by jonathansmirnoff** [bitpay/copay-recovery#130]
I need to recovery founds from a multi sign wallet. The wallets required 2 signers of 3 copayers. I don't understand why this tool asks the 3 seed if I need only 2 to sign the transaction. 
Can anyone explain me this? 
Is there a way to see the source code? I only see here the boundle files

**Comment by matiu** [comment]
Source code is at the master branch:

https://github.com/bitpay/copay-recovery/tree/master

All the public keys are needed, in order to derive the wallet addresses, to scan the funds.

See more at:

https://github.com/bitpay/copay/blob/master/README.md#copay-backups-and-recovery
