### ISSUE TITLE
2 of 3 accounts can't be recovered 

### ISSUE THREAD

**Issue by zikomoto** [bitpay/copay-recovery#24]
Hi , i'm trying copay recovery , and i can recover 3 of 3 accounts , but when using 2 of 3 accounts with the mnemonics in the 3 respective accounts with 2 signatures , i see that the addresses generated to be checked doesn't correspond to their paths for example 
with the mnemonics : 
behind family still perfect aisle tobacco spatial rocket clinic faint siege garlic
balcony anger crack snow skin device waste basic stereo nominee budget clean
warfare either bronze enforce never theory wage cage humble control vibrant oval 

my addresse in path 0 is 3LE3qNjDQ8rQHSH4UCfdjdYorSaZN6jpae
but on the recovery tool i get this adddreess in the same path 
36UixJPeQEyDHxqXQrJgG8qfAgEGNBe5zf

i'm using it wrong or there's a problem ? 

thanks

**Comment by zikomoto** [comment]
Note that I modified a little the code so that I can visualize the addresses creation

**Comment by matiu** [comment]
thanks for the report, let us checkit and we will get back to you.

**Comment by zikomoto** [comment]
thanks

**Comment by gabrielbazan7** [comment]
There was a problem. Now I can see the address that you expect ( 3LE3qNjDQ8rQHSH4UCfdjdYorSaZN6jpae ). Thanks for the report.
