### ISSUE TITLE
Recovery with hardware wallet as a cosigner

### ISSUE THREAD

**Issue by thephez** [bitpay/copay-recovery#36]
This is more of a feature request than an issue.  It would be nice to have a method of getting the account balance and an unsigned transaction for wallets that use a hardware wallet as a cosigner.  Even just getting the account balance per used address based on the public key only exports would be a helpful option.

**Comment by matiu** [comment]
See 
https://github.com/bitpay/copay/blob/master/backupRecovery.md

If you are using the same BWS server were the wallet was created, with only the mnemonic of a software wallet cosigner, you can see the balance.

If you are using a new BWS, with a wallet `export` you can recreate the wallet on the new BWS and see the balance.

**Comment by thephez** [comment]
Thanks. That's exactly what I needed.  I've been doing some wallet restoration testing using testnet multisig accounts and can't restore them from the wallet seed (it generates a "Could not import: Not authorized" error).  I can restore successfully from an export.  

Does the Wallet Seed import not work for Testnet accounts?  The Import Wallet -> Wallet Seed tab does not provide a TestNet switch like the Create tab does so my guess is that it is trying to restore a main network account that doesn't exist from the seed.  

From what I can tell, accounts wallet seed restoration is fine on the main network.
