### ISSUE TITLE
iPad Pro App Generated and Received funds, shortly disappeared afterwords as if first boot

### ISSUE THREAD

**Issue by ridgelawrence** [bitpay/copay-recovery#37]
I have the blockchain info and everything, funds are not accessible - tried everything from restoring backup using word phrase (only backup I had) - on OS X and iPad, along with this tool. 

It's a 1-signer (non-multi) wallet.

Thanks in advance!

**Comment by matiu** [comment]
hi,

what you.mean exactly that funds are not accesible? could.you share a
screenshot?

also, in which address are your funds? so we can check it in the db.

**Comment by ridgelawrence** [comment]
No the coins transferred and are visible and not moving on block chain; I mean, despite this the app has worked great on iPad, but sometime very shortly after receiving funds today on copay for iOS (iPad Pro latest software), the app crashed (no software updates or related actions that would externally cause this) and when I used the given backup phrase for the wallet, it only had ~8 transactions all a month old ago - though I have been using it quite a bit this month. I will email direct support (if I could find their direct email) details that are private (created this thread because no direct support contact info). 

Thanks

**Comment by ridgelawrence** [comment]
@matiu Apologies - didn't notice you were in bitpay org. 

Here's the address: [1LsRmQ3VcZbZ8cDcfzpNjuHeZ8bqTSEW31](https://blockchain.info/address/1LsRmQ3VcZbZ8cDcfzpNjuHeZ8bqTSEW31) 

Thank in advance!

**Comment by ridgelawrence** [comment]
Wallet was restored after some various attempts using similar fixes by users on reddit, for example, and documentation on the main copay app

TY!
