### ISSUE TITLE
Incorrect backup password

### ISSUE THREAD

**Issue by got3nks** [bitpay/copay-recovery#55]
We are trying to recover BCH from a 2-of-3 multisig wallet.

We created the wallet using Bitcore-wallet-client's createWallet("wallet name", "copayer name", 2, 3, {network: 'livenet'}, ...) and two joinWallet(secret, "copayer name", {}, ...).

We have 3 files:
alice.dat
bob.dat
carl.dat

This is what a dat file looks like:
{"network":"livenet","xPrivKey":"...","xPubKey":"...","requestPrivKey":"...","requestPubKey":"...","copayerId":"...","publicKeyRing":[{"xPubKey":"...","requestPubKey":"..."}],"walletId":"...","walletName":"...","m":2,"n":3,"walletPrivKey":"...","personalEncryptingKey":"...","sharedEncryptingKey":"...","copayerName":"...","entropySource":"...","derivationStrategy":"BIP44","account":0,"addressType":"P2SH"}

When we try to use the recover tool we are getting:
**Incorrect backup password**

As far as I know the dat file generated by Bitcore-wallet-client aren't password protected? What is the issue?

**Comment by JDonadio** [comment]
You must to use the encrypted file. These files are unencrypted.

**Comment by got3nks** [comment]
How to use the unencrypted version instead? Or how do I produce the encrypted version, using Bitcore-wallet-client?

**Comment by JDonadio** [comment]
Just use this site: https://bitwiseshiftleft.github.io/sjcl/demo/

Put your backup there and then use encrypt (down arrow) to get the ciphertext.

**Comment by got3nks** [comment]
Thank you, it worked!

**Comment by got3nks** [comment]
Being a large wallet, I've been banned from cashexplorer.bitcoin.com Bitcore API.

*{"status":429,"error":"Rate limit exceeded"}*

Do you have any suggestion, is there any release of Bitcore for BCH available so we can install it on our own servers?
