### ISSUE TITLE
The  BitPay and Copay recovery tool showing Zero balance.

### ISSUE THREAD

**Issue by AlwaysCatch** [bitpay/copay-recovery#56]
I transferred my bitcoins to new wallet, and entered the old wallet seed into BitPay/Copay recovery tool but after scan its showing Zero balance, instead of the old BTC balance. Whose equivalent Bitcoin Cash BCC/BCH I suppose to receive. Can someone please help.

**Comment by JDonadio** [comment]
Are you sure that the transaction was made before the fork?. Are you selecting bch/livenet as main chain to scan your BCH?

**Comment by AlwaysCatch** [comment]
Sorry for Confusion and Thank you for response.
Mistakenly I selected the default chain btc/livenet instead of bch/livenet. It's there now.
Thanks again.
