### ISSUE TITLE
put a wrong address to recover BCH

### ISSUE THREAD

**Issue by azuli11** [bitpay/copay-recovery#57]
So i used the tool to recover my BCH (https://blog.bitpay.com/bitcoin-cash-recovery/amp/) and i wasn't thinking so i sent the recovered BCH to my Copay BTC address... the question is: where the hell are they?! Is there a way to trace the destination?

**Comment by JDonadio** [comment]
Try scanning the same seed again.

**Comment by azuli11** [comment]
thanks that worked!

**Comment by theruddfamily** [comment]
I did the exact same thing but I tried scanning the same seed again and it shows a zero balance. Does it take some time for BCH balance to show up?? TY!!

**Comment by azuli11** [comment]
I think i waited a couple of hours before scanning again. Also make sure
you scan all your wallets in case you have more than 1.

**Comment by theruddfamily** [comment]
Ok I'll try it again tonight.

**Comment by theruddfamily** [comment]
It still shows a zero balance. Any other ideas?
