### ISSUE TITLE
Mnemonic wallet seed not valid

### ISSUE THREAD

**Issue by orbano** [bitpay/copay-recovery#63]
Hi,
I keep having an error message 'mnemonic wallet seed not valid' while trying to scan my wallet.  While my backup phrase seems to be correct (12 words... what other checks could be done?).  The fact that is my phrase is made of french words, containing some accented characters (e.g. 'é').  Could be the origin of the error?  Otherwise, any idea of the origin?
Thanks for feedback.
Olivier

**Comment by JDonadio** [comment]
For spanish the accents are a problem, try matching your words with the french word list: https://github.com/bitcoin/bips/blob/master/bip-0039/french.txt

**Comment by orbano** [comment]
Thanks for the list with the words.
Help me to see where was my mistake!
It works...

**Comment by JDonadio** [comment]
Glad to help!
