### ISSUE TITLE
BCH large wallet: Rate limit exceeded

### ISSUE THREAD

**Issue by got3nks** [bitpay/copay-recovery#65]
Being a large wallet, I've been banned from cashexplorer.bitcoin.com Bitcore API.

_{"status":429,"error":"Rate limit exceeded"}_

Do you have any suggestion, is there any release of Bitcore for BCH available so we can install it on our own servers?

**Comment by nashtu3000** [comment]
Same issue as well, do you have any plans to fix this?

**Comment by got3nks** [comment]
You can now run your own Bitcore node on any Bitcoin fork, https://blog.bitpay.com/bitcore-v5/

Thank you BitPay! <3
