### ISSUE TITLE
Copay shared wallet along with trezor integration for Bitcoin Cash Recovery 

### ISSUE THREAD

**Issue by johnvamo** [bitpay/copay-recovery#68]
I have a copay shared wallet which I use with trezor as they are integrated. (2-2 : two copay users - two required to sign) 

https://blog.bitpay.com/bitcoin-cash-recovery/

I am trying to recover the Bitcoin cash as I have BTC before the hard fork in that wallet.

 https://bitpay.github.io/copay-recovery/

I am asked to put down:  ​Recovery phrase (mnemonic) or File/Text backup. As I am using Trezor along with copay, should it be the trezor seed to be written down there? or what file from trezor or copay wallet should i use?

I am a bit confuse how to takle the recovery.

thanks for your help.

**Comment by alypseak** [comment]
Also searching for a solution to claim using copayers with trezor.  
Does anyone have experience with this?

**Comment by JDonadio** [comment]
Hi guys, please follow https://github.com/bitpay/copay/issues/6789

**Comment by johnvamo** [comment]
Hello, 
I am still not having a clear answer.

now, I am having troubles withdrawing from a copay shared wallet integrated with Trezor... already three days without success. 
Is the any issue? Trezor support says have reported several bugs, which have been checked by them. From their side they said everything is working...advise to contact copay support...please help us...we need urgently to withdraw some funds...thanks for your help.

**Comment by matiu** [comment]
We are working to solve this issue right now. The correct open issue to check  updates is:

https://github.com/bitpay/copay/issues/6957#issuecomment-338650928
