### ISSUE TITLE
can't claim bch using recovery tool

### ISSUE THREAD

**Issue by rickf44** [bitpay/copay-recovery#75]
i tried using the recovery tool to claim my bch

after entering the seed phrase and selecting the correct chain, the tool found my bch and showed the expected balance

on the next screen i entered a valid bch address, but when i click "transfer" i get the red error message

"please enter a valid address"

i have triple checked the address and checked for leading/trailing spaces and even tried reusing a known valid bch address created in bitcoinabc just to make really sure.  i also tried in both chrome and safari, same error.  i use ublock and checked to make sure it was disabled on this page.

the tool won't support any of my bch addresses.  please advise as i'd like to properly secure my bch.

**Comment by matiu** [comment]
Hi. The tool still uses old version numbers for addresses for bch.

With which letter the address starts?

**Comment by rickf44** [comment]
hi! thanks for responding.  i tried these:

14sT_____ (created using bitcoin.com android app)

1LbF_____ (created using bitcoinabc)

1Npv_____ (created using bitcoinabc - this is a known good addresss that previously received funds)

**Comment by rickf44** [comment]
so it turns out the tool expected *new* addresses.  i downloaded a beta of the copay android app and used it to generate a new bch address that starts with a C.  i used thiss in the tool and now i get a different error message:

"Could not build tx: bitcore.ErrorTransactionFeeErrorTooSmall: Fee is too small: expected more than 667 but got 200 - For more information please see: https://bitcore.io/api/lib/transaction#serialization-checks"

what's up with this?  there's nowhere to even set a fee.

this tool seems to be pretty darn broken

**Comment by matiu** [comment]
Hi, thanks for the response.

We will fix that shortly. We will update this ticket once it is fixed.

**Comment by rickf44** [comment]
i think the tool should accept any valid bch address, perhaps it might warn if the address being used is vague, but shouldn't block it

**Comment by matiu** [comment]
we should definitely add a warning/explanation, but accepting addresses with the old version could lead to funds lost if the user uses a Segwit p2sh address.

**Comment by rickf44** [comment]
i understand the logic but literally no apps except the beta version of the copay wallet use the new address format so the old format ought be be usable at least until most wallets have upgraded.   i think a stern warning should suffice.

**Comment by jesusangelm** [comment]
Same issue here using a address starting with "12Fk" from a Keepkey...

**Comment by matiu** [comment]
Rick44 please note you can import directly your seed.in Copay Beta, with
bch support.

**Comment by matiu** [comment]
@rickf44  ^

**Comment by rickf44** [comment]
@matiu I tried this and it failed.  I got an error message but didn't report it  :( sorry.

I noted in the copay beta that the wallet service api for btc and bch are the same.  That seemed incorrect to me, perhaps there is a bug?

**Comment by rickf44** [comment]
@matiu I tried this again.  I installed the copay beta, on the first screen i chose "restore from backup", on next screen i entered my seed words and selected BCH. this time no error but the wallet shows a 0 balance :(

**Comment by rickf44** [comment]
@matiu FYI just to be sure I used the recovery tool again to ensure that the funds are still there.  they're still there, and my seed phrase works.  there's 27+bch so there's more than enough to pay the fees.  trying to send them to copay wallet still produces the "Could not build tx: bitcore.ErrorTransactionFeeErrorTooSmall:" error.  FWIW.

**Comment by jayd3e** [comment]
I'm also experiencing this issue +1.

**Comment by nicaport** [comment]
Also experiencing this issue where the Recovery Tool finds my BCH but cannot transfer it. Tried various valid addresses and still receiving the error 'Please enter a valid address.' At the very least, Copay REALLY needs to put a warning on the recovery page until it is fixed. What is the ETA for this?

Can anyone suggest another splitting tool?

**Comment by JDonadio** [comment]
Can all of you guys try one more time? we recently sent a fix so hopefully will be working ok now.

**Comment by jesusangelm** [comment]
still same issue with message: "Please enter a valid address."

**Comment by nicaport** [comment]
Yes, same here.

**Comment by nicaport** [comment]
Any ETA for a fix?

**Comment by JDonadio** [comment]
## For BCH scan
Please, try using the [translator addresses tool](https://jdonadio.github.io/address-translator/). Once finished the scan process, translate your address and use that new one.

**Comment by nicaport** [comment]
So if you 'translate' the original BCH address and use that one for the transfer, the BCH funds will arrive at the original BCH address? Has this been tested? I don't want to lose any coins.

**Comment by jesusangelm** [comment]
i tried that, 
  the tool translate the BCH address to a new BCH address  starting with "C" the tool worked well for me and i receive at the original BCH address... 

  the unique problem for me is the address translator... this disable the "resultAddress" input and you can not copy the new address... i had to enable it again editing the HTML source code in the DOM.

**Comment by nicaport** [comment]
There is an error icon when hovering above the new address, but I was able to copy it anyway.

**Comment by nicaport** [comment]
And yes, I can confirm that the translation tool works. I received the BCH to the original address. Thank you.

**Comment by nicaport** [comment]
I just tried a second transaction for a much larger amount, and I do not see it on the blocktrail explorer. However, the recovery tool said it was successfully sent. Please help. I sent a large amount, and now there is no trace of it.

**Comment by nicaport** [comment]
@JDonadio @matiu please help

**Comment by matiu** [comment]
@rickf44 The recovery tool accepts BCH address starting wiht C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using https://bitpay.github.io/address-translator/


The Fee problem has been fixed already.

**Comment by nicaport** [comment]
@matiu your response has nothing to do with my question of where my money went. Perhaps you aren't a technical person, but I would like a valid and relevant response to my question as soon as possible.

**Comment by nicaport** [comment]
Is bitpay's new business model to steal money? Because I used the translator tool and recovery tool as dictated in bitpay's posts, but it just swallowed my money - no trace of it on any BCH block explorer.

**Comment by matiu** [comment]
@nicaport my response is for the OP, please feel free to open a new ticket describing your issue.

**Comment by nicaport** [comment]
I cannot claim BCH using your recovery tool. Is that not the subject of this post?

**Comment by matiu** [comment]
it was mentioned already you need to use the translator if you want to send coins to an old BCH address.

If you want more information about your case, please open a ticket providing relevant information so we can check your case.
