### ISSUE TITLE
BCH livenet fails due to CORS header issue

### ISSUE THREAD

**Issue by guzba** [bitpay/copay-recovery#95]
Failed to load https://bch-insight.bitpay.com/api/addr/...?noTxList=1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://bitpay.github.io' is therefore not allowed access. The response had HTTP status code 525.

**Comment by gabrielbazan7** [comment]
We had a problem with our backend. It should be fine now. Sorry for the inconvenience.

**Comment by guzba** [comment]
It does seem to be better thanks very much, but still not working quite perfectly. I've ran it a few times and I am now getting a slightly different response: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://bitpay.github.io' is therefore not allowed access. The response had HTTP status code 429. (The difference is status 429 vs status 525.)

I was able to avoid that error after running it a few times, but once it hits that error the process needs to be restarted (and I only know it is happening by checking the console, there is no UI notification that it will not ever finish.

**Comment by guzba** [comment]
Ah, just hit a 525 as well. Not every time I run it though.

**Comment by gabrielbazan7** [comment]
Sorry, we still having problems with our backend. I will let you know when the tool start working fine again.

**Comment by gabrielbazan7** [comment]
I just send a PR with fix. Could you try now ?

**Comment by guzba** [comment]
I did not run into this the last time I tried. Closing the issue. Thanks for the fix!

**Comment by morenopc** [comment]
I'm getting this error trying to recover BTG (Bitcoin gold)

```
bitpay.github.io/:1 Failed to load 
https://btgexplorer.com/api/addr/GTwHwwe7M2xqUXsExJFQqqzkeGsW4EWvko?noTxList=1: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://bitpay.github.io' is therefore not allowed access.
```

**Comment by kryugger** [comment]
Hello, has anyone managed to solve this problem? Is there an answer?
